resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/10.yaml

packages:
- .

extra-deps:
- gitlib-3.1.3@sha256:7e8f940b380f6155be3bf20be9f363c3bfd3285bd26e0368f406a1c431994598,2935
- gitlib-libgit2-3.1.2.1@sha256:36bc92f117158440ca69e32051aabdf9df75be8a3fb5f45dff8828898e615a0a,2354

# These options are from the Kowainik style guide.
ghc-options:
  "$locals": -Wall -Wcompat -Widentities -Wincomplete-uni-patterns
    -Wincomplete-record-updates -Wredundant-constraints -Wpartial-fields
    -Wmissing-deriving-strategies -Wunused-packages -fno-warn-unused-do-bind
    -fno-warn-orphans -threaded

rebuild-ghc-options: true
allow-newer: true
