resolver: lts-20.1

packages:
- .
- ../gitlib/gitlib
- ../gitlib/gitlib-libgit2


extra-deps:
- ginger-0.10.4.0@sha256:7ca26896395fda951443ed3bba5f24fd6036c44167d424e744d1e0c8c6b138fd,3855
  #- github: jwiegley/gitlib
  #  commit: 1965ed8c198d3c03c43fa0beef2dda67fa3e5d7f
  #  subdirs:
  #    - gitlib
  #    - gitlib-libgit2


ghc-options:
  "gitja": -Wall -Wcompat -Widentities -Wincomplete-uni-patterns
    -Wincomplete-record-updates -Wredundant-constraints -Wpartial-fields
    -Wmissing-deriving-strategies -Wunused-packages -fno-warn-unused-do-bind
    -fno-warn-orphans

rebuild-ghc-options: true
allow-newer: true
