name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        # Fetch all branches and tags so the tests can see them.
        fetch-depth: 0

    - uses: haskell/actions/setup@v1
      with:
        enable-stack: true

    - uses: actions/cache@v2
      with:
        path: ~/.stack/
        key: ${{ runner.os }}-${{ hashFiles('**/stack.yaml.lock') }}

    - name: Build
      run: |
        stack --no-terminal --silent build

    - name: Run tests
      run: |
        bash test/test.sh

    - name: Generate docs
      if: matrix.os == 'ubuntu-latest' && github.event_name == 'push'
      run: |
        sed -i 's/localhost:8000/gitserve.mcol.xyz/' config.dhall
        stack run -- -c ./config.dhall -q

    - name: Deploy docs
      if: matrix.os == 'ubuntu-latest' && github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: output
