name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - uses: haskell/actions/setup@v1
      with:
        enable-stack: true

    - uses: actions/cache@v1
      env:
        cache-name: cache-stack-modules
      with:
        path: ~/.stack/
        key: ${{ runner.os }}-${{ hashFiles('**/stack.yaml.lock') }}

    - name: Build
      run: |
        stack --no-terminal --silent build

    - name: Test
      run: |
        bash test/test.sh
