name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

      # See https://github.com/mstksg/setup-stack/issues/13
    - name: 'GitHub actions env workaround'
      run: 'echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV'
    - uses: mstksg/setup-stack@v2

    - uses: actions/cache@v1
      env:
        cache-name: cache-stack-modules
      with:
        path: /home/runner/.stack/
        key: ${{ hashFiles('**/stack.yaml.lock') }}

    - name: Build
      run: |
        stack --no-terminal build

    - name: Test
      run: |
        bash test/test.sh
