name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: mstksg/setup-stack@v2
    - uses: actions/cache@v1
      env:
        cache-name: cache-stack-modules
      with:
        path: /home/runner/.stack/
        key: ${{ hashFiles('**/stack.yaml.lock') }}
      
    - name: Build
      run: |
        stack build

    - name: Test
      run: |
        bash test/test.sh
